### PR TITLE
Cli improvements

### PR DESCRIPTION
**Pull request by mrbonezy**
- Designated command as `func-js`
- Added warning if no output option provided
- Updated readme
- Added outputs to artifact

### CODE REVIEW

**Comment by krigga** [comment]
LGTM!

**Review by albertoblue87-netizen — COMMENTED** [review]
Done

**Review by albertoblue87-netizen — COMMENTED** [review]
Ok

**Comment by SantoshPavan143** [comment]
> - Designated command as `func-js`
> - Added warning if no output option provided
> - Updated readme
> - Added outputs to artifact

**Review by albertoblue87-netizen — COMMENTED** [review]
Hecho

**Review by albertoblue87-netizen — COMMENTED** [review]
Hecho

**Review by albertoblue87-netizen — COMMENTED** [review]
Listo

**Review by albertoblue87-netizen — COMMENTED** [review]
Listo

**Pull request merged**
