### PR TITLE
wip: added license

### PR DESCRIPTION
**Pull request by Naltox**

### CODE REVIEW

**Review by Behroozomidi — APPROVED** [review]
@Naltox

**Review by Amnat-auyana1998 — COMMENTED** [review]
ton_space_terms_of_use.pdf

**Comment by Amnat-auyana1998** [comment]
ton_space_terms_of_use.pdf

**Review by Amnat-auyana1998 — APPROVED** [review]

**Review by albertoblue87-netizen — COMMENTED** [review]
Hecho

**Pull request merged**
